### ISSUE TITLE
panic: bytes.Buffer: truncation out of range

### ISSUE THREAD

**Issue by Dieterbe** [raintank/tsdb-gw#44]
```
2017/07/25 20:11:54 [I] graphiteProxy: request failed, will retry. context canceled
2017/07/25 20:11:54 http: proxy error: context canceled
2017/07/25 20:11:54 [graphite.go:61 RoundTrip()] [E] graphiteProxy: request failed 3 times. Giving up. context canceled
panic: bytes.Buffer: truncation out of range

goroutine 1095956 [running]:
bytes.(*Buffer).Truncate(0xc4203040e0, 0x0)
	/usr/local/go/src/bytes/buffer.go:74 +0xc1
bytes.(*Buffer).Read(0xc4203040e0, 0xc42118e000, 0x2000, 0x2000, 0x0, 0xc422088840, 0xc422088868)
	/usr/local/go/src/bytes/buffer.go:267 +0xeb
io/ioutil.(*nopCloser).Read(0xc420282700, 0xc42118e000, 0x2000, 0x2000, 0x0, 0xc42171dba0, 0x512287)
	<autogenerated>:1 +0x6b
io/ioutil.devNull.ReadFrom(0x0, 0x7f679ec5ec28, 0xc420282700, 0x88b440, 0xb34101, 0x7f679edfba50)
	/usr/local/go/src/io/ioutil/ioutil.go:144 +0x85
io/ioutil.(*devNull).ReadFrom(0xb8c330, 0x7f679ec5ec28, 0xc420282700, 0x7f679edfba50, 0xb8c330, 0x1)
	<autogenerated>:6 +0x61
io.copyBuffer(0xb36480, 0xb8c330, 0x7f679ec5ec28, 0xc420282700, 0x0, 0x0, 0x0, 0x65, 0x0, 0x0)
	/usr/local/go/src/io/io.go:384 +0x2cb
io.Copy(0xb36480, 0xb8c330, 0x7f679ec5ec28, 0xc420282700, 0x65, 0x0, 0x0)
	/usr/local/go/src/io/io.go:360 +0x68
net/http.(*transferWriter).WriteBody(0xc421828300, 0xb33bc0, 0xc4219f7880, 0x2, 0x2)
	/usr/local/go/src/net/http/transfer.go:324 +0x6c4
net/http.(*Request).write(0xc420144a00, 0xb33bc0, 0xc4219f7880, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:622 +0x6e9
net/http.(*persistConn).writeLoop(0xc4205e8120)
	/usr/local/go/src/net/http/transport.go:1707 +0x1ad
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1118 +0xa5a
panic: bytes.Buffer: truncation out of range

goroutine 1095806 [running]:
bytes.(*Buffer).Truncate(0xc4203040e0, 0x0)
	/usr/local/go/src/bytes/buffer.go:74 +0xc1
bytes.(*Buffer).Read(0xc4203040e0, 0xc4209f4000, 0x2000, 0x2000, 0x0, 0xc422088420, 0xc422088448)
	/usr/local/go/src/bytes/buffer.go:267 +0xeb
io/ioutil.(*nopCloser).Read(0xc420282700, 0xc4209f4000, 0x2000, 0x2000, 0x0, 0xc421428ba0, 0x512287)
	<autogenerated>:1 +0x6b
io/ioutil.devNull.ReadFrom(0x0, 0x7f679ec5ec28, 0xc420282700, 0x88b440, 0xb34101, 0x7f679edfba50)
	/usr/local/go/src/io/ioutil/ioutil.go:144 +0x85
io/ioutil.(*devNull).ReadFrom(0xb8c330, 0x7f679ec5ec28, 0xc420282700, 0x7f679edfba50, 0xb8c330, 0x1)
	<autogenerated>:6 +0x61
io.copyBuffer(0xb36480, 0xb8c330, 0x7f679ec5ec28, 0xc420282700, 0x0, 0x0, 0x0, 0x65, 0x0, 0x0)
	/usr/local/go/src/io/io.go:384 +0x2cb
io.Copy(0xb36480, 0xb8c330, 0x7f679ec5ec28, 0xc420282700, 0x65, 0x0, 0x0)
	/usr/local/go/src/io/io.go:360 +0x68
net/http.(*transferWriter).WriteBody(0xc420824180, 0xb33bc0, 0xc4209a6bc0, 0x2, 0x2)
	/usr/local/go/src/net/http/transfer.go:324 +0x6c4
net/http.(*Request).write(0xc420144a00, 0xb33bc0, 0xc4209a6bc0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:622 +0x6e9
net/http.(*persistConn).writeLoop(0xc4200fe240)
	/usr/local/go/src/net/http/transport.go:1707 +0x1ad
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1118 +0xa5a
```

**Comment by Dieterbe** [comment]
interestingly only these 2 goroutines in the panic stacktrace.

**Comment by replay** [comment]
Just had the same:
```
panic: bytes.Buffer: truncation out of range

goroutine 21049297 [running]:
bytes.(*Buffer).Truncate(0xc4201c5490, 0x0)
        /usr/local/go/src/bytes/buffer.go:74 +0xc1
bytes.(*Buffer).Read(0xc4201c5490, 0xc4200ce000, 0x2000, 0x2000, 0xc4202c0de0, 0xc421edc160, 0xc421999b58)
        /usr/local/go/src/bytes/buffer.go:267 +0xeb
io/ioutil.(*nopCloser).Read(0xc4206b0d00, 0xc4200ce000, 0x2000, 0x2000, 0x0, 0xc421999ba0, 0x4e79d7)
        <autogenerated>:1 +0x6b
io/ioutil.devNull.ReadFrom(0x0, 0x7fd2ba984aa0, 0xc4206b0d00, 0x90b6e0, 0xc13101, 0x7fd2ba984b90)
        /usr/local/go/src/io/ioutil/ioutil.go:144 +0x85
io/ioutil.(*devNull).ReadFrom(0xc6d340, 0x7fd2ba984aa0, 0xc4206b0d00, 0x7fd2ba984b90, 0xc6d340, 0x1)
        <autogenerated>:6 +0x61
io.copyBuffer(0xc15d40, 0xc6d340, 0x7fd2ba984aa0, 0xc4206b0d00, 0x0, 0x0, 0x0, 0xb0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:384 +0x2cb
io.Copy(0xc15d40, 0xc6d340, 0x7fd2ba984aa0, 0xc4206b0d00, 0xb0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:360 +0x68
net/http.(*transferWriter).WriteBody(0xc4200b9d00, 0xc12c40, 0xc420650cc0, 0x2, 0x2)
        /usr/local/go/src/net/http/transfer.go:324 +0x6c4
net/http.(*Request).write(0xc4212a0800, 0xc12c40, 0xc420650cc0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/request.go:622 +0x6e9
net/http.(*persistConn).writeLoop(0xc420f74360)
        /usr/local/go/src/net/http/transport.go:1707 +0x1ad  
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1118 +0xa5a
```

**Comment by Dieterbe** [comment]
```
2017/10/20 15:04:00 [I] graphiteProxy: request to graphite:8080 failed, will retry: context canceled
2017/10/20 15:04:00 [I] graphiteProxy: request to graphite:8080 failed, will retry: context canceled
panic: bytes.Buffer: truncation out of range

goroutine 22644741 [running]:
bytes.(*Buffer).Truncate(0xc420fe53b0, 0x0)
	/usr/local/go/src/bytes/buffer.go:74 +0xc1
bytes.(*Buffer).Read(0xc420fe53b0, 0xc420e9a000, 0x2000, 0x2000, 0x0, 0xc422b020b0, 0xc422b020d8)
	/usr/local/go/src/bytes/buffer.go:267 +0xeb
io/ioutil.(*nopCloser).Read(0xc420256940, 0xc420e9a000, 0x2000, 0x2000, 0x0, 0xc420ffdba0, 0x4e79d7)
	<autogenerated>:1 +0x6b
io/ioutil.devNull.ReadFrom(0x0, 0x7fc45a655868, 0xc420256940, 0x90b6e0, 0xc13101, 0x7fc45a655958)
	/usr/local/go/src/io/ioutil/ioutil.go:144 +0x85
io/ioutil.(*devNull).ReadFrom(0xc6d340, 0x7fc45a655868, 0xc420256940, 0x7fc45a655958, 0xc6d340, 0x1)
	<autogenerated>:6 +0x61
io.copyBuffer(0xc15d40, 0xc6d340, 0x7fc45a655868, 0xc420256940, 0x0, 0x0, 0x0, 0x1b1, 0x0, 0x0)
	/usr/local/go/src/io/io.go:384 +0x2cb
io.Copy(0xc15d40, 0xc6d340, 0x7fc45a655868, 0xc420256940, 0x1b1, 0x0, 0x0)
	/usr/local/go/src/io/io.go:360 +0x68
net/http.(*transferWriter).WriteBody(0xc4207c8180, 0xc12c40, 0xc420de0400, 0x2, 0x2)
	/usr/local/go/src/net/http/transfer.go:324 +0x6c4
net/http.(*Request).write(0xc420adf500, 0xc12c40, 0xc420de0400, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:622 +0x6e9
net/http.(*persistConn).writeLoop(0xc4201c5d40)
	/usr/local/go/src/net/http/transport.go:1707 +0x1ad
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1118 +0xa5a
```

need to investigate more, but some thoughts so far:
* seems triggered when the response claims to have more data than contentlength, so it tries to read more data.
* according to the stacktrace, the buffer calls `Truncate(0)` when `if b.off >= len(b.buf)`, however then it panics when `0 > len(b.buf) - b.off`, so somehow the offset or len gets modified concurrently.
* seems related to our retry logic. could be `outreq.Body = ioutil.NopCloser(bytes.NewBuffer(body))` which reuses the same slice in subsequent attempts.
