### ISSUE TITLE
fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by Dieterbe** [raintank/tsdb-gw#62]
version fdf757e
interestingly, seems to happen in the standard http library.
could be related to some of the jaeger context stuff which puts stuff in http headers

```
fatal error: concurrent map iteration and map write
2018/01/11 14:02:02 [I] graphiteProxy: request to graphite-17303-large-foo:8080 failed, will retry: context canceled

goroutine 167005 [running]:
runtime.throw(0x9ad065, 0x26)
        /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc420984a38 sp=0xc420984a18
runtime.mapiternext(0xc420984ba0)
        /usr/local/go/src/runtime/hashmap.go:737 +0x7ee fp=0xc420984ae8 sp=0xc420984a38
net/http.Header.sortedKeyValues(0xc420b38900, 0xc4200276e0, 0xc420029000, 0x7f7f292a28d0, 0xc420029000, 0x1)
        /usr/local/go/src/net/http/header.go:135 +0x203 fp=0xc420984c10 sp=0xc420984ae8
net/http.Header.WriteSubset(0xc420b38900, 0xc12c40, 0xc420029000, 0xc4200276e0, 0x0, 0x1)
        /usr/local/go/src/net/http/header.go:152 +0xbe fp=0xc420984d48 sp=0xc420984c10
net/http.(*Request).write(0xc4206def00, 0xc12c40, 0xc420029000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/request.go:577 +0x580 fp=0xc420984e88 sp=0xc420984d48
net/http.(*persistConn).writeLoop(0xc42321e7e0)
        /usr/local/go/src/net/http/transport.go:1707 +0x1ad fp=0xc420984fd8 sp=0xc420984e88
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420984fe0 sp=0xc420984fd8
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1118 +0xa5a

goroutine 1 [chan receive, 60 minutes]:
main.main()
        /home/ubuntu/.go_workspace/src/github.com/raintank/tsdb-gw/main.go:139 +0x753

goroutine 5 [syscall, 60 minutes]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 7 [select]:
github.com/raintank/tsdb-gw/vendor/github.com/raintank/worldping-api/pkg/log.(*Logger).StartLogger(0xc4201ac5c0)
        /home/ubuntu/.go_workspace/src/github.com/raintank/tsdb-gw/vendor/github.com/raintank/worldping-api/pkg/log/log.go:234 +0x2a7
created by github.com/raintank/tsdb-gw/vendor/github.com/raintank/worldping-api/pkg/log.newLogger
        /home/ubuntu/.go_workspace/src/github.com/raintank/tsdb-gw/vendor/github.com/raintank/worldping-api/pkg/log/log.go:167 +0x11f

```

**Comment by Dieterbe** [comment]
can confirm, disabling jaeger tracing keeps the tsdgw's from crashing

**Comment by Dieterbe** [comment]
hmmmm
```
	// RoundTrip must always close the body, including on errors,
	// but depending on the implementation may do so in a separate
	// goroutine even after RoundTrip returns. This means that
	// callers wanting to reuse the body for subsequent requests
	// must arrange to wait for the Close call before doing so.
	//
	// The Request's URL and Header fields must be initialized.
	RoundTrip(*Request) (*Response, error)
```

only question is, what Close call is it talking about. Neither the RoundTrip interface, nor the Request struct has a Close method.

**Comment by Dieterbe** [comment]
seems related to #44 also

**Comment by Dieterbe** [comment]
had this patch in my working copy, but not committed. not sure what this was
```
diff --git a/graphite/graphite.go b/graphite/graphite.go
index c626ab8..9c93d3e 100644
--- a/graphite/graphite.go
+++ b/graphite/graphite.go
@@ -66,6 +66,7 @@ func (t *proxyRetryTransport) RoundTrip(outreq *http.Request) (*http.Response, e
                }
 
                res, err = t.transport.RoundTrip(outreq)
+               outreq.Close()
                attempt_span.Finish()
                if err == nil {
                        break
```
